version: '3'

services:
    api:
        build: ./backend
        container_name: ${APP_NAME}_api
        ports:
            - 127.0.0.1:${FLASK_PORT}:5000
        volumes:
            - './backend:/app'
        command: >
            sh -c "python /app/wsgi.py"
