FORMAT: 1A

# Group Auth

## Auth Collection [/auth]

### Authentificate [POST]

+ username (string) - A username
+ password (string) - The corresponding password

    + Request with body (application/json)

           {
               "password": "michel",
               "username": "salut123"
           }

+ Response 200 (application/json)

    + Body

           {
               "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.rrJleHAiOjE1ODU3MjQxNjQsImlhdCI6MTU4NTcyMzg2NCwibmJmIjoxNTg1NzIzODY0LCJpZGVudGl0eSI6MX0.cy_lZqPwcvq6g-28gdMubcN4IqkDSgCzM5weRFi3yh0"
           }


# Group Query

## Query bills [/bill]

### Query bills [GET]

+ paid: (string, optional) - Search for bills that has/hasn't been paid
+ client: (string, optional) - Search for bills with the selected client name

+ Request
    
    + Headers

           Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.rrJleHAiOjE1ODU3MjQxNjQsImlhdCI6MTU4NTcyMzg2NCwibmJmIjoxNTg1NzIzODY0LCJpZGVudGl0eSI6MX0.cy_lZqPwcvq6g-28gdMubcN4IqkDSgCzM5weRFi3yh0

+ Response 200 (application/json)

    + Body

            [
                {
                    "client": {
                        "city": "Villers-la-Ville",
                        "name": "Michel",
                        "postal_code": 1495,
                        "street": "Rue de la tour",
                        "street_number": "42",
                        "vat_number": "babar"
                    },
                    "date": "Tue, 31 Mar 2020 00:00:00 GMT",
                    "expiration": "Tue, 31 Mar 2020 00:00:00 GMT",
                    "paid": false,
                    "price": 300.0
                },
                {
                    "client": {
                        "city": "Louvain-la-Neuve",
                        "name": "Babar",
                        "postal_code": 1348,
                        "street": "Avenue du Ciseau",
                        "street_number": "42",
                        "vat_number": "babar"
                    },
                    "date": "Tue, 31 Mar 2020 00:00:00 GMT",
                    "expiration": "Tue, 31 Mar 2020 00:00:00 GMT",
                    "paid": false,
                    "price": 300.0
                }
            ]
