FORMAT: 1A
HOST: https://facturesoft.ovh/api

# Bill API
This an API documentation of our web application.

<!-- include(./users/index.apib) -->
<!-- include(./clients/clients.apib) -->
<!-- include(./bills/bills.apib) -->
