# Group Bills

## Bills [/bills]

### Create a bill [POST]

+ Request (application/json)
    + Headers
        Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        
    + Attributes (object)
        + client_id: 456 (number)
        + number: 98765 (number)
        + date: 20/05/2021 (string)
        + expiration: 21/05/2021 (string)
        + price: 123456 (number)
        + cash: true (boolean)
        + paid: true (boolean)
      
+ Response 201 (application/json)
    + Attributes (object)
        + message: Created (string)      
 

+ Response 200 (application/json)
    + Body
        ["const","babar","tortue"]


## Bills [/bills/delete]

### Delete a bill [DELETE]

+ Request (application/json)
    + Headers
        Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

+ Response 200 (application/json)
    + Attributes (object)
        + message: Deleted (string)

+ Response 404 (application/json)
    + Attributes (object)
        + message: Bill does not exists (string) 
